### ISSUE TITLE
建议 yanzhenjie  的库都不要用。 随时可能不再维护弃坑

### ISSUE THREAD

**Issue by lks6123** [yanzhenjie/Kalle#119]
用过的几个库都弃坑了。几年未维护过，建议大家不要用。。。

**Comment by yanzhenjie** [comment]
![image](https://user-images.githubusercontent.com/13534988/114683196-6900e200-9d42-11eb-942f-98955562a7a1.png)
有道理，给你点赞

**Comment by lks6123** [comment]
实话实说罢了， NoHttp .  AndPermission, SwipeRecyclerView   用过的几个都这样了。  项目里前面同事用的时候不做好封装， 后面遇到坑，麻烦的要死，被坑惨了。

**Comment by liangjingkanji** [comment]
> ![image](https://user-images.githubusercontent.com/13534988/114683196-6900e200-9d42-11eb-942f-98955562a7a1.png)
> 有道理，给你点赞

你把我挂README, 我帮你维护吧: [Net](https://github.com/liangjingkanji/Net)

**Comment by TomatoWithEgg** [comment]
> > ![image](https://user-images.githubusercontent.com/13534988/114683196-6900e200-9d42-11eb-942f-98955562a7a1.png)
> > 有道理，给你点赞
> 
> 你把我挂README, 我帮你维护吧: [Net](https://github.com/liangjingkanji/Net)

还是把内核换了吧,别用Kalle

**Comment by yanzhenjie** [comment]
> 实话实说罢了， NoHttp . AndPermission, SwipeRecyclerView 用过的几个都这样了。 项目里前面同事用的时候不做好封装， 后面遇到坑，麻烦的要死，被坑惨了。

不维护的几k的star的库蛮多的，你也没必要来专门喷我吧，目前就是不能投入太多时间来维护。而且源码就在这里，你觉得原作者后来不符合你期望了你随时可以自己改，这也是开源的意义之一，自己被坑了解决不了问题就来喷开源作者也没必要吧。

**Comment by liangjingkanji** [comment]
> > 实话实说罢了， NoHttp . AndPermission, SwipeRecyclerView 用过的几个都这样了。 项目里前面同事用的时候不做好封装， 后面遇到坑，麻烦的要死，被坑惨了。
> 
> 不维护的几k的star的库蛮多的，你也没必要来专门喷我吧，目前就是不能投入太多时间来维护。而且源码就在这里，你觉得原作者后来不符合你期望了你随时可以自己改，这也是开源的意义之一，自己被坑了解决不了问题就来喷开源作者也没必要吧。

那你直接"归档", 而且你也没有接受其他人的PR.  我觉得还是有一定的责任的

**Comment by lks6123** [comment]
> > 实话实说罢了， NoHttp . AndPermission, SwipeRecyclerView 用过的几个都这样了。 项目里前面同事用的时候不做好封装， 后面遇到坑，麻烦的要死，被坑惨了。
> 
> 不维护的几k的star的库蛮多的，你也没必要来专门喷我吧，目前就是不能投入太多时间来维护。而且源码就在这里，你觉得原作者后来不符合你期望了你随时可以自己改，这也是开源的意义之一，自己被坑了解决不了问题就来喷开源作者也没必要吧。

晚上想了下 ， 是我被前人留的坑气的有点冲动了， 向您道歉。 毕竟开源项目确实只是一个个人的行为。
