### ISSUE TITLE
文件下载的时候，当服务器找不到文件的时候返回404码

### ISSUE THREAD

**Issue by YangSimon** [yanzhenjie/Kalle#18]
下载回调不走onException方法，而是走onFinish方法，返回path路径，path就是请求url地址，并且会在设定的目录下创建这个路径文件

**Comment by yanzhenjie** [comment]
404是正常响应，因此创建文件，并写入服务端返回的内容，这是正确的。

这是框架，不是软件，因此具体的业务需要你来处理，请看看文档。

**Comment by yanzhenjie** [comment]
看一下文档，使用下载策略可以写下载相关业务。
