### ISSUE TITLE
0.1.3版本 特殊字符的参数值需要解码两次

### ISSUE THREAD

**Issue by wuyifengWYF** [yanzhenjie/Kalle#21]
参数值为 MI 4C,23,6.0.1
打印的地址值变为了MI%25204C%252C23%252C6.0.1服务端需要解码两次才能拿到原参数值
编码一次的结果应该为MI+4C%2c23%2c6.0.1

**Comment by yanzhenjie** [comment]
请帖一下请求的完整代码，参数值请明确写出，不要使用变量代替。

**Comment by wuyifengWYF** [comment]
Application中的配置.      
 
 KalleConfig.Builder builder = KalleConfig.newBuilder();
       builder.network(new BroadcastNetwork(getApplicationContext()))
                 .connectFactory(OkHttpConnectFactory.newBuilder().build())
                .addInterceptor(new RetryInterceptor(1))
                .addInterceptor(new LoggerInterceptor("Kalle===>", true)) 
                .converter(new JsonConverter(this)) 
                .connectionTimeout(30000, TimeUnit.MILLISECONDS)          
                .readTimeout(30000, TimeUnit.MILLISECONDS)
                .addParam("osVer", "MI 4C,23,6.0.1");=======>就是这个参数值
        KalleConfig config = builder.build();
        Kalle.setConfig(config);

实际请求:
  Kalle.get(" http://xxxxxxx.com")
                .perform(new SimpleCallback<List<Banner>>() {
                    @Override
                    public void onResponse(SimpleResponse<List<Banner>, String> simpleResponse) {
                       
                        if (simpleResponse.isSucceed()) {//Http成功,业务也成功
                           
                        } else {
                            
                        }
                    }

                });

控制台打印:
 Print Request: http://xxxx?osVer=MI%25204C%252C23%252C6.0.1
    Method: GET.
    Accept: */*.
    Accept-Encoding: gzip, deflate.
    Accept-Language: zh-CN,zh.
    Connection: keep-alive.
    Content-Type: application/x-www-form-urlencoded.
    User-Agent: Mozilla/5.0 (Linux; U; Android 6.0.1; en; MI 4C Api/MMB29M) AppleWebKit/534.30 (KHTML, like Gecko) Version/5.0 Mobile Safari/534.30.

**Comment by yanzhenjie** [comment]
你好，主要就是想看完整的请求代码，最重要的就是url部分和参数部分，你可能隐藏了什么吧。

根据你目前贴出的代码，我可以保证绝对不会发生这个问题。

**Comment by wuyifengWYF** [comment]
1.Application的配置       
 KalleConfig.Builder builder = KalleConfig.newBuilder();
        //配置全局网络，用来让Kalle检查网络是否可用，如果不配置将会默认网络是可用的。
        builder.network(new BroadcastNetwork(getApplicationContext()))
                //配置全局连接生成工厂，决定底层使用OkHttp、UrlConnection或者HttpClient
                .connectFactory(OkHttpConnectFactory.newBuilder().build())
                //设置全局重试拦截器  失败后重试一次
                .addInterceptor(new RetryInterceptor(1))
                //设置全局日志拦截器  打印日志
                .addInterceptor(new LoggerInterceptor("Kalle===>", true))
                //全局转换器
                .converter(new JsonConverter(this))
                //全局连接服务器超时时间
                .connectionTimeout(30000, TimeUnit.MILLISECONDS)
                //全局响应服务器返回的超时时间
                .readTimeout(30000, TimeUnit.MILLISECONDS)
                //当前系统版本号
                .addParam(getString(R.string.params_osver), "MI 4C,23,6.0.1")
                // 客户端的版本号
                .addParam(getString(R.string.params_appver), "3.7.4")
                // 客户端的类型
                .addParam(getString(R.string.params_devicetype), "android")
                // 客户端的ID
                .addParam(getString(R.string.params_deviceid), "865687025963651")
                // 用户类型
                .addParam("userType", "1")
                //城市ID
                .addParam("2");
        if (isLogin() && getAcUsr() != null) {
            builder.addParam(getString(R.string.params_sessionkey), getAcUsr().getSessionKey());
        }

        KalleConfig config = builder.build();
        Kalle.setConfig(config);

2.  Kalle.get("http://api.sit.licai66.com/v2/api/banner/list")
                .perform(new SimpleCallback<List<com.msfly.financing.client.bean.Banner>>() {
                    @Override
                    public void onResponse(SimpleResponse<List<com.msfly.financing.client.bean.Banner>, String> simpleResponse) {
                       
                        if (simpleResponse.isSucceed()) {//Http成功,业务也成功
                     
                        } else {
                         
                        }
                    }

                });
3.控制台打印
08-22 17:10:11.254 25437-25987/Kalle===>:  
    Print Request: http://api.sit.licai66.com/v2/api/banner/list?osVer=MI%25204C%252C23%252C6.0.1&appVer=3.7.4&deviceType=android&deviceId=865687025963651&userType=1&cityId=2.
    Method: GET.
    Accept: */*.
    Accept-Encoding: gzip, deflate.
    Accept-Language: zh-CN,zh.
    Connection: keep-alive.
    Content-Type: application/x-www-form-urlencoded.
    User-Agent: Mozilla/5.0 (Linux; U; Android 6.0.1; en; MI 4C Api/MMB29M) AppleWebKit/534.30 (KHTML, like Gecko) Version/5.0 Mobile Safari/534.30.
08-22 17:10:11.421 25437-25987//Kalle===>:  
    Print Response: http://api.sit.licai66.com/v2/api/banner/list?osVer=MI%25204C%252C23%252C6.0.1&appVer=3.7.4&deviceType=android&deviceId=865687025963651&userType=1&cityId=2.
    Code: 200
    Access-Control-Allow-Origin: *.
    Cache-Controll: no-cache.
    Connection: keep-alive.
    Content-Encoding: gzip.
    Content-Type: application/json;charset=UTF-8.
    Date: Wed, 22 Aug 2018 09:10:12 GMT.
    Expires: Thu, 01 Jan 1970 00:00:00 GMT.
    Okhttp-Response-Source: NETWORK 200.
    Okhttp-Selected-Protocol: http/1.1.
    Pragma: no-cache.
    Server: nginx/1.9.2.
    Transfer-Encoding: chunked.

**Comment by yanzhenjie** [comment]
:broken_heart: 你好，我是想看...的部分（如果有的话），是我没有描述清楚吗？
```
Kalle.get("http://api.sit.licai66.com/v2/api/banner/list?...")
...
.perform();
```

**Comment by yanzhenjie** [comment]
抱歉，应该全局添加的参数吧，这是一个bug，我争取今天修复这个问题并发布一个新版本。

**Comment by wuyifengWYF** [comment]
那我上传的代码我都删了啊!多谢严大.我是群里自己人
