### ISSUE TITLE
关于okhttp cookies维护的问题

### ISSUE THREAD

**Issue by iota9star** [yanzhenjie/Kalle#22]
我通过源码发现kalle的cookies维护是在ConnectInterceptor里面动态添加，如果其他库需要用到同一个okhttp实例，例如fresco,glide等图片加载库，就不会有cookies的维护，所以这个okhttp实例还需要自行实现一个cookiejar? 如果我没有猜测错的话，这就会导致一个问题，cookies会被保存两次，然后请求时添加两次，感觉这样并不是太合理，我觉得这个cookies的维护应该单独抽象出来，可以提供默认的实现，用户也可以实现自己的维护逻辑

**Comment by yanzhenjie** [comment]
可以自己实现，看下文档。

**Comment by iota9star** [comment]
第三方库使用okhttp实例不会得到cookies维护，只有个人实现cookiejar，同时kalle不设置cookiestore，才能避免被添加两次
