### ISSUE TITLE
开启DeBug拦截器能不能每次请求的提交的参数也打出来

### ISSUE THREAD

**Issue by niyaode** [yanzhenjie/Kalle#26]
.addInterceptor(new LoggerInterceptor("Kalle", BuildConfig.DEBUG))//Debug拦截器

**Comment by yanzhenjie** [comment]
根据你的描述，你应该是想打印Body里面的参数吧，因为自带的Logger拦截器不确定你发送的是什么Body，你可以自行实现一个拦截器，获取到Body后instanceof一下，做个打印即可。

**Comment by bebetter1030** [comment]
@yanzhenjie 
```UrlBody```的```mParams```是私有属性，获取不到...
```copyParams()```方法也是私有方法

**Comment by yanzhenjie** [comment]
@bebetter1030   Got it.
