### ISSUE TITLE
大佬，是否支持多文件下载

### ISSUE THREAD

**Issue by WildChen** [yanzhenjie/Kalle#27]

**Comment by yanzhenjie** [comment]
提供的下载功能，可以同时下载多个文件。

**Comment by WildChen** [comment]
多个文件同时下载的时候，回调并不知道对应哪个下载。

**Comment by yanzhenjie** [comment]
这个很简单，把Callback封成一个基类，给一个int值的成员变量，每次new的时候传一个值进去，回调时回调出来就可以了，相当于Wrapper了一下。

**Comment by WildChen** [comment]
好的，多谢老哥 :+1:
