### ISSUE TITLE
调用Kalle.cancel(tag)方法时，有时会出现android.os.NetworkOnMainThreadException错误

### ISSUE THREAD

**Issue by xxx1012** [yanzhenjie/Kalle#28]

**Comment by xxx1012** [comment]
另外，貌似在网络不稳定的情况下，当调用cancel方法时，并没有取消请求，过了一段时间会出现com.yanzhenjie.kalle.exception.ReadTimeoutError错误

**Comment by MAFEILIN** [comment]
![kalle](https://user-images.githubusercontent.com/17745618/50408280-e5deb980-0822-11e9-98cf-76aa7f9a927f.png)
