### ISSUE TITLE
请求类型application/x-www-form-urlencoded;charset=UTF-8如何修改为application/json;charset=UTF-8 

### ISSUE THREAD

**Issue by orangegithub1** [yanzhenjie/Kalle#31]
全局配置时替换过了，后端收到的还是application/x-www-form-urlencoded;charset=UTF-8请求

**Comment by yanzhenjie** [comment]
全局配置只能附加头，不能替换Http标准的头。

你传`JsonBody`会自动变为`application/json`，或者自定义Body，在`contentType()`方法中返回你想发送的值就可以了。
