### ISSUE TITLE
关于业务封装

### ISSUE THREAD

**Issue by Joslyn-Chen** [yanzhenjie/Kalle#33]
业务封装不够灵活，为什么非要给失败的时候定义一个类型呢？

**Comment by yanzhenjie** [comment]
去掉就灵活了吗？加上可以选择要或者不要，根据自己的业务来决定。目前我遇到的绝大多开发者都是要的，不要以偏概全。

**Comment by Joslyn-Chen** [comment]
@yanzhenjie 在wiki的业务封装页面，Http成功，业务也成功的情况下，拿不到Message了，SimpleResponse类也没有存放Message的方法，也不能继承。
`if (httpEntity.getCode() == 1) { // 服务端业务成功。
                try {
                    succeedData = JSON.parseObject(httpEntity.getData(), succeed);
                } catch (Exception e) {
                    failedData = (F) "服务器数据格式异常";
                }
            } else {
                // 业务失败，获取服务端提示信息。
                failedData = (F) httpEntity.getMessage();
            }`
