### ISSUE TITLE
当App处于打开状态，长时间不操作，再次操作时会频现com.yanzhenjie.kalle.exception.NetworkError错误

### ISSUE THREAD

**Issue by xxx1012** [yanzhenjie/Kalle#36]
网络连接正常，就是总报com.yanzhenjie.kalle.exception.NetworkError，除非关闭App，重新打开才恢复正常

**Comment by zhengzaihong** [comment]
@xxx1012    今天我也遇到了这个问题了，你怎么解决的？

**Comment by zhengzaihong** [comment]
@yanzhenjie 这个问题已经closed了 不过还是会浮现。有啥好的解决方案没？  比如，再次初始化下网络框架？
