### ISSUE TITLE
SimpleCallback直接使用Test对象，response.succeed()返回null,什么情况呢！

### ISSUE THREAD

**Issue by douya40** [yanzhenjie/Kalle#38]
Kalle.post(UrlConfig.LOGIN)
                .param("name", model.getAccount())
                .param("password", model.getPassword())
                .perform(new SimpleCallback<String>(BaseApplication.getInstance()) {
                    @Override
                    public void onResponse(SimpleResponse<String, String> response) {
                        Test test = JSON.parseObject(response.succeed(), Test.class);
                        callback.onDataLoaded(test);
                    }
                });
----------------------------------------------------------------------------------------------------
public class Test {
    /**
     * code : 200
     * succeed : true
     */
    @JSONField(name = "code")
    private int code;
    @JSONField(name = "succeed")
    private boolean succeed；
    public int getCode() {
        return code;
    }
    public void setCode(int code) {
        this.code = code;
    }
    public boolean isSucceed() {
        return succeed;
    }
    public void setSucceed(boolean succeed) {
        this.succeed = succeed;
    }
}
--------------------------------------
SimpleCallback<Test>   SimpleResponse<Test, String>  Test test= response.succeed()-->返回null,什么情况呢？

**Comment by yanzhenjie** [comment]
需要使用Converter，不需要自己在主线程解析数据，Kalle会在子线程帮你解析，具体请多看看文档。
