### ISSUE TITLE
大哥，这个HTTP网络框架好多坑

### ISSUE THREAD

**Issue by btxd** [yanzhenjie/Kalle#40]
我用您的的框架有些手机报域名不能解析，我换一个网络框架一点问题都没有，真坑；

**Comment by zhouzhiguang** [comment]
严大处理一下bug

**Comment by yanzhenjie** [comment]
底层是OkHttp还是URLConnection？不能解析跟框架无关，这个是系统层做的。

**Comment by btxd** [comment]
OKhttp，我使用原生的OKhttp一点问题都没有，使用您的框架，有些设备，怎么都是网络域名无法解析，切换网络也是一样，我后台BUG日志也检测到很多这种情况

**Comment by btxd** [comment]
项目使用人少根本看不出来，几万用户，这些BUG全出来了

**Comment by yanzhenjie** [comment]
你的底层是设置的OkHttp？使用Kalle必先？使用原生OkHttp不会出现？

**Comment by fairytale110** [comment]
提问能不能直接点，代码不贴，日志不贴，这提的都什么issue。。。

**Comment by yanzhenjie** [comment]
系统层解析的，一般都是DNS服务器的问题，换框架到这些出问题的手机上，一样会出现。
