### ISSUE TITLE
Interceptor中Response的结果正常，但是SimpleCallback中response.succeed()为空

### ISSUE THREAD

**Issue by 740852294** [yanzhenjie/Kalle#44]
Interceptor中Response的结果正常，返回的数据是正确的，但是SimpleCallback中response.succeed()为空

**Comment by yanzhenjie** [comment]
配置converter了吗？尽量一次把问题描述完。

**Comment by 740852294** [comment]
我在Application里面添加了一个登陆拦截器
拦截器代码：
`@Override
    public Response intercept(Chain chain) throws IOException {
        Request request = chain.request();
        Response originResponse = chain.proceed(request);
        String result = originResponse.body().string();
        Log.e("originResponse", result);
        return originResponse;
    }`
我只是在里面加了两行这个
`       String result = originResponse.body().string();
        Log.e("originResponse", result);`
在Callback的onResponse里面 response.succeed()结果就成为空了
这两行去掉  response.succeed()的数据又有了

**Comment by yanzhenjie** [comment]
ReponseBody只能被读取一次，如果想统一打印响应Body，请在Converter中转化数据时打印，Request信息和Response信息，可以加一个Logger拦截器，请参考Demo。

**Comment by bebetter1030** [comment]
分开打印有点怪，```ResponseBody```能否提供一个clone```byteArray()```的方法？这样Interceptor里可以clone一次再打印。

另，我自行复制了一个```LoggerInterceptor```，删除了每行日志结尾的```.```，之前第一次看的时候吓一跳，怎么url后面自动多了```.```。这个问题不大，算个人习惯。

**Comment by kunnzhou886** [comment]
我也遇到同样问题，Interceptor 中拦截打印后，Converter 中就读不到response中body 获取为空

**Comment by yanzhenjie** [comment]
#62
