### ISSUE TITLE
用手机4G流量上传文件报错WriteException

### ISSUE THREAD

**Issue by fairytale110** [yanzhenjie/Kalle#47]
List<Binary> binaries = new ArrayList<>(); // 文件list。

        for (int i = 0; i < result.size(); i++) {
            FileBinary binary = new FileBinary(new File(result.get(i).getPath()));
            binaries.add(binary);
        }

        FormBody formBody = FormBody.newBuilder()
                //.param("from", "Android")
                .param("docType", fileType)
                .binaries("file",binaries)
                .build();
        formBody.onProgress(progressBar);

        Kalle.post(API.getFILL_UPLOAD())
                .tag(System.currentTimeMillis())
                .body(formBody)
                .path(system)
                .readTimeout(10,TimeUnit.MINUTES)
                .connectTimeout(10,TimeUnit.HOURS)
                .addHeader("enctype", Headers.VALUE_APPLICATION_FORM)
                //.setHeader(Headers.KEY_CONTENT_TYPE, Headers.VALUE_APPLICATION_FORM + ";boundary=" + UUID.randomUUID().toString())
                .perform(callback);

**Comment by fairytale110** [comment]
宽带WIFI不会有问题

**Comment by fairytale110** [comment]
![image](https://user-images.githubusercontent.com/30248926/50954393-2ad84080-14f1-11e9-85f3-2a187bd6c24d.png)


![image](https://user-images.githubusercontent.com/30248926/50954416-3af02000-14f1-11e9-8e07-fb856070e2c8.png)

**Comment by yanzhenjie** [comment]
超时了呀，不是文件被占用就是网络不好，链接服务器不稳定。大多数是后者。

**Comment by fairytale110** [comment]
图片选择用的您的Album库，应该不存在文件被占用吧？网络应该不会有问题吧，4G网也不慢，外网WI-FI都能成功上传。刚刚试了下本地局域网也有这个问题。好蛋疼，甲方要演示。

**Comment by fairytale110** [comment]
这是我的图片选择封装方法

![image](https://user-images.githubusercontent.com/30248926/50955115-42182d80-14f3-11e9-9363-e35fb88b7103.png)


这是我调用的地方


![image](https://user-images.githubusercontent.com/30248926/50955196-6f64db80-14f3-11e9-8235-25da261228fa.png)


这是我的上传业务部分


![image](https://user-images.githubusercontent.com/30248926/50955253-94594e80-14f3-11e9-8fb0-bad5a37b5313.png)


请教下我这样的使用是否存在问题而导致报错呢？

**Comment by fairytale110** [comment]
你好，在kalle在Application初始化时设置了超时为3分钟，如图，这样是有效的吗，但是好像对问题提到的报错没有什么影响，大概三十秒不到就报错了。


![image](https://user-images.githubusercontent.com/30248926/50956160-ff0b8980-14f5-11e9-847d-e67afae15ccd.png)

**Comment by yanzhenjie** [comment]
我前面看错分钟成秒了，你的超时时间并不短。

看你使用的OkHttp作为底层，我搜了一下，这个有可能是OkHttp的问题：
[https://github.com/square/okhttp/issues/3974](https://github.com/square/okhttp/issues/3974)

你把底层切换为URLConnection试试看这个问题还出现吗，另外URLConnection作为底层时，在Android4.4以下的系统中，DELETE请求不支持上行body。

**Comment by fairytale110** [comment]
果然是OkHttp的坑，换成
```
AppConfig.get().initFileDir();
            Kalle.setConfig(KalleConfig.newBuilder()
                    .connectFactory(URLConnectionFactory.newBuilder().build())
                    .cookieStore(DBCookieStore.newBuilder(this).build())
                    .cacheStore(DiskCacheStore.newBuilder(AppConfig.get().PATH_APP_CACHE).build())
                    .network(new BroadcastNetwork(this))
                    //.addInterceptor(new LoginInterceptor())//自动重新登录拦截器
                    // 可以添加 请求失败自动重试拦截器
                    .addInterceptor(new LoggerInterceptor("EB-HTTP", BuildConfig.DEBUG))
                    .addInterceptor(new RetryInterceptor(3))
                    .converter(new JsonConverter(this))
                    .connectionTimeout(3, TimeUnit.MINUTES)
                    .readTimeout(3, TimeUnit.MINUTES)
                    .build());
````

**Comment by fairytale110** [comment]
就可以了，十分感谢您
