### ISSUE TITLE
[UNCHECKED_CAST] Unchecked cast: String! to F

### ISSUE THREAD

**Issue by duxun** [yanzhenjie/Kalle#51]
failedData = httpEntity.mMessage as F
Kotlin 我这样转换的时候编译出问题 ： Unchecked cast: String! to F

**Comment by yanzhenjie** [comment]
不知道你的响应消息结构和你的数据类型是什么样的，没法帮到你。

另外语法和编译问题不属于本项目问题，你可以去别处咨询一下。
