### ISSUE TITLE
请求数据出现不正常的现象

### ISSUE THREAD

**Issue by BugMen** [yanzhenjie/Kalle#52]
按照文档配置完Kalle后，有个使用场景是，get请求，用.path()拼接了url地址，然后请求回来的数据每次都是相同的，（类似点赞或者关注功能，直接在请求地址后拼接用户id，请求回的数据应该是在true和false之间切换，但现在请求回的每一次都一样）但是我直接用OKHttp请求就可以拿到正确的数据，用postman或者其他都是正确的，这是什么导致的啊？？？很急很关键！

**Comment by yanzhenjie** [comment]
抓包看数据，如果每次都是`false`，那么可能是`converter`发生了异常，默认值是`false`。

以下是示例：
```java
if (succeed == Integer.class) {
    Integer succeedInt = Integer.parseInt(data);
    succeedData = (S)succeedInt;
} else if (succeed == Long.class) {
    Long succeedLong = Long.parseLong(data);
    succeedData = (S)succeedLong;
} else if (succeed == String.class) {
    succeedData = (S)data;
} else if (succeed == Boolean.class) {
    Boolean succeedBoolean = Boolean.parseBoolean(data);
    succeedData = (S)succeedBoolean;
}  else {
    succeedData = JSON.parseObject(data, succeed);
}
```

**Comment by BugMen** [comment]
不是，我的意思是，可以正常返回数据，但是每次请求回来的数据都是不变的。比如说点赞和取消点赞这个功能，正常来讲应该是每次请求都是有变化的，但是现在请求回来的是不变的。我用OKHttp原生的就没问题

**Comment by yanzhenjie** [comment]
恩明白。现在问题的具体原因还不确定，比如是converter那里异常了？参数没有正确提交？服务端没有正确返回？抓包是为了确定问题发生的具体原因，找不到原因，就算有问题，我也没法解决。

**Comment by BugMen** [comment]
是啊，我也挺头疼的，同样的地址，参数在POSTMAN或者其他地方都好使，而且只有http://example/{id}这种类型的接口去请求点赞关注这种功能时才会出问题，而且是拿到response.body().string()就已经不对了，有点无奈

**Comment by yanzhenjie** [comment]
抓包了吗？你说的这些都是表现层，相对不太能确定问题。

**Comment by BugMen** [comment]
抓了呀，就是只能看到表现，因为在response里就直接返回了结果，所以不知道问题出在哪，有没有可能是配置的问题？

**Comment by yanzhenjie** [comment]
既然抓包了，就看抓包的上行url、请求头、请求方法和参数，再看下行的响应头、响应码、响应包体，如果都没有问题，应该是业务逻辑的问题，如果是框架提交参数和你编写代码的预期不一致，那么可能是框架修改了你的请求头或者参数，你试试这样排查问题。

**Comment by BugMen** [comment]
![image](https://user-images.githubusercontent.com/15857673/55790236-82854880-5aee-11e9-9017-9f2c9640462a.png)
这个是我请求的参数，实际只有Authorization是主要参数， 在postman或其他请求工具上请求都没问题

**Comment by yanzhenjie** [comment]
我已经告诉你排查方法了，除非你找到问题原因，否则我没法帮助你。

**Comment by BugMen** [comment]
解决了，竟然是因为Log拦截器的问题，我之前把文档上拦截器的代码改了点，竟然会出现这种问题，太神奇了。。。

**Comment by BugMen** [comment]
还有个问题啊，关于Kalle的配置，您是建议放在application里还是放在baseActivity里？

**Comment by yanzhenjie** [comment]
就算你调用多次初始化，也只有第一次的初始化会生效，我一般放在`Application`中。

**Comment by BugMen** [comment]
那比如配置的时候需要添加token到header中，一般token都是用SharedPreferences保存在本地嘛，当你进入程序的时候，配置全局header是从SharedPreferences里取token，然后你退出登录（但是不退出程序）的时候清空token，此时，其他请求里的token依旧是有值的没有被清空，这要怎么解决呢？

**Comment by yanzhenjie** [comment]
使用拦截器，在拦截器中做参数签名、加密和添加请求头等操作，在Demo中有演示，文档应该也有写到。

**Comment by BugMen** [comment]
OK，学到了，感谢大佬！
