### ISSUE TITLE
添加header问题

### ISSUE THREAD

**Issue by 18819318753** [yanzhenjie/Kalle#56]
你好，我在全局里面配置了header，是一个sessionId，但是这个sessionId是用户登录完才会返回的，返回后，我需要把这个放在header里面，但此时全局配置已经初始化了，我应该如何刷新全局配置呢？难道是重新初始化配置吗？

**Comment by YoungHappy** [comment]
Kalle.getConfig().getHeaders().set("XX-Token", Account.getInstance().getToken());   
正好刚遇到这个问题

**Comment by yanzhenjie** [comment]
这种情况下一般在拦截器添加，做一个专门做参数签名加密的拦截器，把登陆后的需要的通用参数和通用头添加进去就可以了。
