### ISSUE TITLE
打开demo报错

### ISSUE THREAD

**Issue by Founder005** [yanzhenjie/Kalle#57]
一开始提示minsdk 不能低于26 我就改成了26
改完之后报这个错误
Process: com.yanzhenjie.kalle.sample, PID: 9370  
 java.lang.BootstrapMethodError: Exception from call site #6 bootstrap method ，

我用的gradle4.6，跟这个和有关系么？

**Comment by yanzhenjie** [comment]
kalle的 minSdkVersion是9，sample的minSdkVersion是14。应该是你的本地构建环境问题，例如SDK版本缺失之类的引起。
