### ISSUE TITLE
GET请求抛出异常

### ISSUE THREAD

**Issue by 15534408044** [yanzhenjie/Kalle#58]
同一个请求接口，用POST调试是通的，用GET请求一直Callback  Exception ，java.lang.AssertionError: It should not be called.
用Postman测试Get跟POST请求都是通的

**Comment by yanzhenjie** [comment]
这是因为调用了Url类型Request的生成body的方法，这类请求是没有body，比如GET、HEAD等请求。发生的原因可能是你封装时哪里调用了这个方法：`UrlRequest#body()`，可能在签名或者拦截器之类的地方，你排查解决即可。
