### ISSUE TITLE
url中含有中文，需要指定的编码格式“gb2312”

### ISSUE THREAD

**Issue by androidflying** [yanzhenjie/Kalle#60]
默认的是按照utf-8转换的。
我把url的中文转成url编码之后，框架会再次编码

**Comment by androidflying** [comment]
@Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        Set<String> keySet = keySet();
        for (String key : keySet) {
            List<Object> values = get(key);
            for (Object value : values) {
                if (value != null && value instanceof CharSequence) {
              ----->      String textValue = Uri.encode(value.toString());//这里把编码之后的文字又进行了编码
                    builder.append("&").append(key).append("=").append(textValue);
                }
            }
        }
        if (builder.length() > 0) builder.deleteCharAt(0);
        return builder.toString();
    }

**Comment by androidflying** [comment]
Params类 ，152行。

**Comment by androidflying** [comment]
是不是可以指定编码格式？或者不进行编码，从业务层做处理？

**Comment by yanzhenjie** [comment]
不能，该操作符合Url编码规范，本框架暂不支持自定义，你可以下载源码自行修改。
