### ISSUE TITLE
Url的处理，api末尾的“/”被处理掉

### ISSUE THREAD

**Issue by chenzijie20** [yanzhenjie/Kalle#64]
当服务器的api必须是 xxx.com/api/xxx/  时，末尾的斜杠在这里被处理掉了。
if (!TextUtils.isEmpty(path)) {
            while (path.startsWith("/")) path = path.substring(1);
            while (path.endsWith("/")) path = path.substring(0, path.length() - 1);
            String[] pathArray = path.split("/");
            Collections.addAll(pathList, pathArray);
        }
该机制导致一直返回301重定向，不能正确请求接口，这种api写法在服务端是存在的

**Comment by yanzhenjie** [comment]
没办法，让他们改改吧。

**Comment by chenzijie20** [comment]
谢谢你的回复，我自己在代码那边处理了一下



czj@kapokcloud.com
 
发件人： Zhenjie Yan
发送时间： 2019-06-24 15:22
收件人： yanzhenjie/Kalle
抄送： chenzijie; Author
主题： Re: [yanzhenjie/Kalle] Url的处理，api末尾的“/”被处理掉 (#64)
没办法，让他们改改吧。
―
