### ISSUE TITLE
Interceptor 中如何添加新的参数

### ISSUE THREAD

**Issue by niyaode** [yanzhenjie/Kalle#65]
我的需求是这样的。我的参数都RSA加密。
先把提交的参数变成JOSN字符串，然后RSA加密成字符串。
最后在设置一个新的参数来装加密的字符串，
现在我找不到如何设置新的参数

**Comment by yanzhenjie** [comment]
拦截器中不要使用原来的Request对象，使用一个新的Request对象，添加加密和签名后的参数发起请求返回结果就行。
