### ISSUE TITLE
关于拦截器里添加新参数

### ISSUE THREAD

**Issue by animus198656** [yanzhenjie/Kalle#69]
拦截器中不要使用原来的Request对象，使用一个新的Request对象，添加加密和签名后的参数发起请求返回结果就行。

_Originally posted by @yanzhenjie in https://github.com/yanzhenjie/Kalle/issues/65#issuecomment-504890633_

创建新的Request之后，原来的参数怎么处理？重新添加的新Request的话，全局参数会被添加两遍；不重新添加的话，某个请求单独配置的参数会丢失 @yanzhenjie

**Comment by yanzhenjie** [comment]
```java
Request request = chain.request();
Params params = request.copyParams(); // 原来的参数，含初始化时的全局参数
RequestMethod method = request.method(); // 原来的请求方法

Response response = chain.proceed(request);
if(...) { // 一些登录的业务逻辑
    return response;
} else {
    Request newRequest = BodyRequest.newBuilder(request.url(), request.method())
        .setParams(params) // 设置参数，会覆盖新对象的所有参数
        .build();

    Call call = new Call(newRequest);
    Response response = call.execute();

    ... // 一些业务处理

    return chain.proceed(request);
}
```
以上代码能否解决你的问题？

**Comment by animus198656** [comment]
这样可以，多谢多谢

**Comment by java02014** [comment]
> ```java
> Request request = chain.request();
> Params params = request.copyParams(); // 原来的参数，含初始化时的全局参数
> RequestMethod method = request.method(); // 原来的请求方法
> 
> Response response = chain.proceed(request);
> if(...) { // 一些登录的业务逻辑
>     return response;
> } else {
>     Request newRequest = BodyRequest.newBuilder(request.url(), request.method())
>         .setParams(params) // 设置参数，会覆盖新对象的所有参数
>         .build();
> 
>     Call call = new Call(newRequest);
>     Response response = call.execute();
> 
>     ... // 一些业务处理
> 
>     return chain.proceed(request);
> }
> ```
> 
> 以上代码能否解决你的问题？

这个在新的请求的同时不能阻止原来的请求，会产生两次请求，这个怎么破？
