### ISSUE TITLE
为什么我用SimpleResponse只能把泛型写成String才能用

### ISSUE THREAD

**Issue by berial** [yanzhenjie/Kalle#76]
如果是String类型，response.success()就有值，然后需要用Gson生成对象；
如果直接写成相应对象，response.success()就为空

**Comment by yanzhenjie** [comment]
提供的信息不足够判断问题和提供帮助。

**Comment by ttxz** [comment]
感觉描述的问题是数据映射吧！你看你用的转换器，直接映射成对象是需要有转换器的，默认的转换器是转换成了String类型的。

**Comment by berial** [comment]
> 
> 
> 感觉描述的问题是数据映射吧！你看你用的转换器，直接映射成对象是需要有转换器的，默认的转换器是转换成了String类型的。

多谢
