### ISSUE TITLE
日志Interceptor无法打印body内容

### ISSUE THREAD

**Issue by ghost** [yanzhenjie/Kalle#78]
设置日志拦截器, body内容无法打印.
 设置okhttp的body拦截,框架里居然没有用到它.  

能否加个body的克隆功能,可以在日志拦截器里打印下.

**Comment by yanzhenjie** [comment]
https://github.com/yanzhenjie/Kalle/blob/master/kalle/src/main/java/com/yanzhenjie/kalle/connect/http/LoggerInterceptor.java
