### ISSUE TITLE
您好，长时间停留APP，会出现提示“网络不可用”

### ISSUE THREAD

**Issue by 18819318753** [yanzhenjie/Kalle#79]
您好，长时间停留在APP上，会出现提示“网络不可用”，但是我退出APP，使用其他APP，是有网络的。我需要重新断开网络，再连上，APP才会有网络。

**Comment by yanzhenjie** [comment]
网络检查使用`RealTimeNetwork `替换原来的`BroadcastNetwork`可解决这个问题。
